#ifndef QI_GUI_H
#define QI_GUI_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Create a new window
 *
 * # Arguments
 * * `title` - Window title (UTF-8 string)
 * * `width` - Window width
 * * `height` - Window height
 *
 * # Returns
 * Window handle (ID), or 0 on error
 */
uint64_t qi_gui_create_window(const char *title, uint32_t width, uint32_t height);

/**
 * Destroy a window
 *
 * # Arguments
 * * `window_id` - Window handle
 */
void qi_gui_destroy_window(uint64_t window_id);

/**
 * Set window title
 *
 * # Arguments
 * * `window_id` - Window handle
 * * `title` - New title (UTF-8 string)
 */
void qi_gui_set_title(uint64_t window_id, const char *title);

/**
 * Get window title
 *
 * # Arguments
 * * `window_id` - Window handle
 *
 * # Returns
 * Title string (must be freed with qi_gui_free_string)
 */
char *qi_gui_get_title(uint64_t window_id);

/**
 * Show window
 *
 * # Arguments
 * * `window_id` - Window handle
 */
void qi_gui_show_window(uint64_t window_id);

/**
 * Hide window
 *
 * # Arguments
 * * `window_id` - Window handle
 */
void qi_gui_hide_window(uint64_t window_id);

/**
 * Check if window is visible
 *
 * # Arguments
 * * `window_id` - Window handle
 *
 * # Returns
 * 1 if visible, 0 if not
 */
int32_t qi_gui_is_visible(uint64_t window_id);

/**
 * Run the event loop (blocking)
 * This should be called from the main thread
 */
void qi_gui_run(void);

/**
 * Free a string allocated by this library
 *
 * # Arguments
 * * `s` - String pointer to free
 */
void qi_gui_free_string(char *s);

/**
 * Get library version
 *
 * # Returns
 * Version string (must be freed with qi_gui_free_string)
 */
char *qi_gui_version(void);

#endif  /* QI_GUI_H */
